# Site settings
# in the templates available like {{ site.myvariable }}.
title: The Portfolio of Seth Goldfarb
email: goldfarbas@gmail.com
brand: Seth Goldfarb
headline: Welcome to my Portfolio
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
copyright: 2019 All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contact
email: goldfarbas@gmail.com
phone: (https://www.linkedin.com/in/asethgoldfarb/)
twitter: [@goldenchaosgod](https://twitter.com/GoldenChaosGod)

# Tracking
googleAnalitycsID: UA-38411253-5

